In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(type(a))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
l1=[1,2,3,4,5]
l2=[4,3,2,1,5]
a=np.array(l1)
b=np.array(l2)
print(a*b)

[ 4  6  6  4 25]


In [ ]:
import numpy as np
l1=[1,2,3,4,5]
l2=[4,3,2,1,5]
a=np.array(l1)
b=np.array(l2)
print(a*b)
print(a.ndim)
print((a*b).ndim)

[ 4  6  6  4 25]
1
1


In [ ]:
import numpy as np
x=np.array([[2,3,4],[3,7,5]])
y=np.array([[3,5,4],[7,4,2]])
s=x+y
print(s)

[[ 5  8  8]
 [10 11  7]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5], ndmin=5)

print(arr)
print("number of ddimensions: ", arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of ddimensions:  5


In [ ]:
import numpy as np
a=np.arange(start=0, stop=10, step=1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
a=np.arange(0,10,1)
print(a)
a

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
a=np.arange(start=1, stop=2, step=0.1)
print(a)
a

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
# row , coloumn

import numpy as np
a=np.array([[1,2,3,4],[6,5,4,3]])
a.shape

(2, 4)

In [ ]:
# layer , row , coloumn

import numpy as np
a=np.array([[[1,2,3,4],[6,5,4,3],[4,5,6,7]]])
a.shape

(1, 3, 4)

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

print("")

b=a.reshape(3,2)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5])
lt=[1,2,3,4,5]
print("List elements ar: ",lt)
print(type(lt))
print("--------------------------")
print("Array elements ar: ",arr)
print(type(arr))

List elements ar:  [1, 2, 3, 4, 5]
<class 'list'>
--------------------------
Array elements ar:  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr= np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
bool_array=np.array(True)

print("0-d array:",bool_array)
print("number of dimensions (ndim): ",bool_array.ndim)
print("shape of the array (shape): ",bool_array.shape)
print("total number of elements (size): ",bool_array.size)
print("data type of element (dtype): ",bool_array.dtype)

0-d array: True
number of dimensions (ndim):  0
shape of the array (shape):  ()
total number of elements (size):  1
data type of element (dtype):  bool


In [ ]:
import numpy as np

a=np.array(7)
b=np.array(3)

sum_result=a+b
product_result=a*b

print("sum of 0-d arrays: ",sum_result)
print("product of 0-d arrays: ",product_result)

sum of 0-d arrays:  10
product of 0-d arrays:  21


In [ ]:
# convarting 0-d array to scalar value


import numpy as np
array=np.array(99)

scalar_value=array.item()
print("0-d array: ",array)
print("type of 0-d array: ",type(array))
print('')

print("scalar_value: ",scalar_value)
print("type of scalar_value: ",type(scalar_value))

0-d array:  99
type of 0-d array:  <class 'numpy.ndarray'>

scalar_value:  99
type of scalar_value:  <class 'int'>


In [ ]:
# converting scalar back to array

import numpy as np

scalar_valu=99
array=np.array(scalar_value)


print(type(scalar_valu))
print(scalar_valu)
print("")
print(type(array))
print(array)

<class 'int'>
99

<class 'numpy.ndarray'>
99


In [ ]:
# slicing

import numpy as np
a=np.array([10,20,30,40,50])
s=a[1:4]

print(a)
print("sliced array: ",s)

[10 20 30 40 50]
sliced array:  [20 30 40]


In [ ]:
# adding a integer with array
# multiplying number with array
a=np.array([10,20,30,40,50])

add=a+10
mult=a*2

print(add)
print(mult)

[20 30 40 50 60]
[ 20  40  60  80 100]


1.print an array range b/w 1 to 100 and show 50 random numbers

In [ ]:
# print an array range b/w 1 to 100 and show 50 random numbers

import numpy as np
r=np.random.randint(1,100,50)

print(r)
print(type(r))

[12 91 83 88 54 94 94 49 26 11 30 23 80 96 51 17 15 26 24 73 11 51 77 11
 55 98  6 45 42 74 98 93 12 34 93 76 32 81 63 41 78 12 53 26 70  2 65 18
 40 20]
<class 'numpy.ndarray'>


In [ ]:
# 2-d array matrix

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
int64


In [ ]:
# accsesing elements from 2-d array

a=np.array([[1,2,3],[4,5,6],[7,8,9]])

element=a[1,2]
f=a[2,0]
g=a[1,0]
h=a[0,0]
print(a)

print("------------accsesing item--------------")

print(element)  # row=1 and coloumn=2
print(f)        # row=2 and coloumn=0
print(g)        # row=1 and coloumn=0
print(h)        # row=0 and coloumn=0

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------accsesing item--------------
6
7
4
1


In [ ]:
# accsesing rows

a=np.array([[1,2,3],[4,5,6],[7,8,9]])

b=a[0,:]
c=a[1,:]
d=a[2,:]

print(b)     # accsesing first row
print("")
print(c)     # accsesing second row
print("")
print(d)     # accsesing third row

[1 2 3]

[4 5 6]

[7 8 9]


In [ ]:
# accsesing coloumns

a=np.array([[1,2,3],[4,5,6],[7,8,9]])

b=a[:,0]
c=a[:,2]

print(b)         # accsesing first coloumn
print(c)         # accsesing third coloumn

[1 4 7]
[3 6 9]


In [ ]:
# adding two matrices

import numpy as np
a=np.array([[1,2,3,4],[3,4,5,6]])
b=np.array([[5,6,4,3],[4,9,8,0]])

c=a+b
print(c)

[[ 6  8  7  7]
 [ 7 13 13  6]]


In [ ]:
# multiplying two matrices

import numpy as np

a=np.array([[1,2,3,4],[3,4,5,6]])
b=np.array([[5,6,4,3],[4,9,8,0]])
r=np.multiply(a,b)
print(r)

[[ 5 12 12 12]
 [12 36 40  0]]


In [ ]:
# transpose of matrix

import numpy as np

a=np.array([[1,2,3,4],[3,4,5,6]])

print(a)
print("")
d=np.transpose(a)
print(d)
print("")

# finding the transpose of matrix using the .T attribute

print(a.T)

[[1 2 3 4]
 [3 4 5 6]]

[[1 3]
 [2 4]
 [3 5]
 [4 6]]

[[1 3]
 [2 4]
 [3 5]
 [4 6]]


In [ ]:
# creating a 3-d array

import numpy as np

array_3d=np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,18]]])

print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


can access elements in 3-d array using three idices [depth,row,coloumn]

In [ ]:
import numpy as np

array_3d=np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,18]]])

element=array_3d[1,0,2]    # [depth=1 , row=0 , coloumn=2]  using index number
n=array_3d[0,1,0]          # [depth=0 , row=1 , coloumn=0]  using index number
m=array_3d[2,0,0]          # [depth=2 , row=0 , coloumn=0]  using index number

print(array_3d)

print('')    # print('') for skip lines
print('')
print('')

print(element)
print(n)
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]



9
4
13


accessing a specific matrix(2-d slice) in the 3-d array

In [ ]:
import numpy as np

array_3d=np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,18]]])

b=array_3d[1]
n=array_3d[2]

print(array_3d)

print('')    # print('') for skip lines
print('')
print('')

print(b)   # second layer (1th index)
print('')
print(n)  #third layer (2th index)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]



[[ 7  8  9]
 [10 11 12]]

[[13 14 15]
 [16 17 18]]


slicing 3-d array

In [ ]:
# slicing the 3-d array to get sub array



sub=array_3d[:2,1:,:2]    #slicing the first two matrices (2 layers (index 0,1 layers)), second row (1th index starting) ,and first 2 coloumns (0,1 index)
sub1=array_3d[:3,:1,:2]
sub2=array_3d[1:2,:1,1:]
sub3=array_3d[2:,1:,2:]



print(array_3d)

print('')
print('')

print(sub)
print("--------------------------- sub1 ----------------------")
print(sub1)
print("--------------------------- sub2 ----------------------")
print(sub2)
print("--------------------------- sub3 ----------------------")
print(sub3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


[[[ 4  5]]

 [[10 11]]]
--------------------------- sub1 ----------------------
[[[ 1  2]]

 [[ 7  8]]

 [[13 14]]]
--------------------------- sub2 ----------------------
[[[8 9]]]
--------------------------- sub3 ----------------------
[[[18]]]


In [ ]:
import numpy as np

# creating a 3x3 matrix with values ranging from 2 to 10
# and reshaping it to 3x3 matrix

x=np.arange(2,11)
print(x)
print("diomension: ",x.ndim)
print("shape: ",x.shape)

print('')
print('')

a=np.arange(2,11).reshape(3,3)
print(a)
print("diomension: ",a.ndim)
print("shape: ",a.shape)

[ 2  3  4  5  6  7  8  9 10]
diomension:  1
shape:  (9,)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
diomension:  2
shape:  (3, 3)
