# - use np.zeros() - use np.ones()  - np.eye()

2.how do you crate an array with all values as zero  and ones                   
    - use np.zeros()                                                            
    - use np.ones()

In [ ]:
import numpy as np


a=np.zeros(5)          # for 1-d array
print(a)

print('')

b=np.zeros((2,2))       # for 2-d array
print(b)

print('')

c=np.zeros((2,2,2))    # for 3-d array
print(c)

[0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]]

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
# 1-d zero array

array_1d_zeros=np.zeros(5)
print(array_1d_zeros)


[0. 0. 0. 0. 0.]


In [ ]:
# 2-d zero array

array_2d_zeros=np.zeros((3,4))
print(array_2d_zeros)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 3-d zero array

array_3d_zeros=np.zeros((2,3,4))
print(array_3d_zeros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
import numpy as np

array_1d_ones=np.ones(5)
print("1-d array of ones: ",array_1d_ones)


array_2d_ones=np.ones((3,4))
print("2-d array of ones: ",array_2d_ones)


array_3d_ones=np.ones((2,3,4))
print("3-d array of ones: ",array_3d_ones)

1-d array of ones:  [1. 1. 1. 1. 1.]
2-d array of ones:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3-d array of ones:  [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# numpy .eye method

import numpy as np

# 2x2 matrix with 1's on main diagonel
a=np.eye(2)
print("matrix a: \n",a)

b=np.eye(3)
print("\n matrix b: \n",b)


# matrix with 4 row and 5 coloumn
# when k=-1 , below main diagonel
c=np.eye(4,5,k=-1)
print("\n matrix c : \n ",c )


# matrix with 4 row and 5 coloumn
# when k=-1 , above main diagonel
c=np.eye(4,5,k=1)
print("\n matrix c : \n ",c )

matrix a: 
 [[1. 0.]
 [0. 1.]]

 matrix b: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 matrix c : 
  [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

 matrix c : 
  [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# **numpy array indexing**                                                        
access array elements                                                           


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


get two element and add them

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0]+arr[3])

5


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]*arr[3])

12


In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print("\n",a[1,-1])
print("\n",a[1,-3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 10

 8


In [ ]:
# qustion.1
import numpy as np
a=np.zeros(10)
print(a)

a[5]=11
print(a)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [ ]:
# qs. 2. create an array with avlues ranging from 12 to 38
import numpy as np

a=np.arange(12,38)
print(a)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# slicing

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[4:])

[5 6 7]


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[:4])

[1 2 3 4]


negative slicing

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[-3:-1])

[5 6]


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[1:5:2])

[2 4]


In [ ]:
import numpy as np

a=np.array([12,34,54,645,76,345,56])
print(a[1:5:2])

[ 34 645]


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[::2])
# step is 2 , start and stop will be default

[1 3 5 7]


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7])
print(a[:4:])

[1 2 3 4]


In [ ]:
import numpy as np

a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,1:4])

[7 8 9]


In [ ]:
import numpy as np

a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0,1:3])

[2 3]


In [ ]:
import numpy as np

a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(a)
print("\n",a[0:2,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 [3 8]


In [ ]:
import numpy as np

a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(a)
print("\n",a[0:2,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 [[2 3 4]
 [7 8 9]]


# question

In [ ]:
import numpy as np

a=np.ones((4,4))
print(a)

a[1:3,1:3]=0
print("\n",a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
a=np.zeros((5,5))


# set the border values to 1
a[0,:]=1        # top border
a[-1,:]=1       # bottom border
a[:,0]=1        # left border
a[:,-1]=1       # right border

print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Create a 4x4 matrix and fill it with checkerboard pattern

In [ ]:
import numpy as np

a=np.ones((4,4))
print(a)

a[0,1]=0
a[0,3]=0
a[1,0]=0
a[1,2]=0
a[2,1]=0
a[2,3]=0
a[3,0]=0
a[3,2]=0


print("\n",a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


In [ ]:
import numpy as np

# create a 4x4 matrix with ones
a=np.ones((4,4))
print(a)
# fill the matrix with checkboard pattern

a[1::2,::2]=0      # select every second row, starting from the second row (index=1)
                   # select every second coloumn, starting from first coloumn (index=0)

a[::2,1::2]=0      # select every second row, starting from the second row (index=0)
                   # select every second coloumn, starting from first coloumn (index=1)



print("\n",a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


# - use np.nonzero()

3.get the values and indices of the elements that are bigger than 10 in given array                                                                           
                                                                                                                                                                -.nonzero() ,returns the indices of the elements that are non-zero

In [ ]:
import numpy as np

x=np.array([[0,10,20],[20,30,40]])

print("original array: \n",x)
print('')
print("values bigger than 10: ",x[x > 10])            # filtering values bigger than 10
print('')
print("their indices ar: ",np.nonzero((x > 10)))      # get indices of the elements that are bigger than 10 using np.nonzero()

print("\n this means:   \n -20 at index(0,2) \n -20 at index(1,0) \n -30 at index(1,1) \n -40 at index(1,2)")

original array: 
 [[ 0 10 20]
 [20 30 40]]

values bigger than 10:  [20 20 30 40]

their indices ar:  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

 this means:   
 -20 at index(0,2) 
 -20 at index(1,0) 
 -30 at index(1,1) 
 -40 at index(1,2)


find the values greater than 100 and it's indices

In [ ]:
import numpy as np

a=np.array([[106,107,99,67,110],[26,76,96,200,101],[1,2,202,75,60]])

print(a)
print("\n values bigger than 100: \n",a[a > 100])

[[106 107  99  67 110]
 [ 26  76  96 200 101]
 [  1   2 202  75  60]]

 values bigger than 100: 
 [106 107 110 200 101 202]


# - use np.round()

4.Numpy program to convert celsius to fahrenheit

In [ ]:
# converting celcius to farenheit

import numpy as np

c=np.array([0,12,45.21,34,99.91])

print("values in celsius degrees: \n",c)

print("values in farenheit degrees: ")
print(np.round((9*c/5 + 32),2))

values in celsius degrees: 
 [ 0.   12.   45.21 34.   99.91]
values in farenheit degrees: 
[ 32.    53.6  113.38  93.2  211.84]


In [ ]:
# converting celcius to kelvin

import numpy as np

c=np.array([0,12,45.21,34,99.91])

print("values in celsius degrees: \n",c)

print("\n values in kelvin degrees: ")
print(np.round((c+273.15),2))

values in celsius degrees: 
 [ 0.   12.   45.21 34.   99.91]

 values in kelvin degrees: 
[273.15 285.15 318.36 307.15 373.06]


In [ ]:
# converting farenheit to celcius

import numpy as np

f=np.array([32, 53.6, 113.38, 93.2, 211.84])

print("values in farenheit degrees: \n",f)

print("\n values in celcius degrees: ")
print(np.round((5/9 * (f-32)),2))

values in farenheit degrees: 
 [ 32.    53.6  113.38  93.2  211.84]

 values in celcius degrees: 
[ 0.   12.   45.21 34.   99.91]


# data types in Numpy



• i-integer                                                                     
• b-boolean                                                                     
• u- unsigned integer                                                           
• f- float                                                                      
• c- complex float                                                              
• m-timedelta                                                                   
• M-datetime                                                                    
• O-object                                                                      
• S-string                                                                      
• U - unicode string                                                            
• V - fixed chunk of memory for other type (void)                 

# **cheking the data type of an array**

- The Numpy array object has a property called dtype that returns the data typeof the array

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [ ]:
import numpy as np

ar=np.array(['apple','banana','cherry'])
print(ar.dtype)

<U6


# **creating arrays with a defined data type**

- we use the array() function to create arrays, this function can **take an optional argument: dtype that allows us to define the expected data type of the array elements**

In [ ]:
import numpy as np

arr=np.array([1,2,3,4], dtype='S')

print(arr)
print("\n",arr.dtype)

[b'1' b'2' b'3' b'4']

 |S1


for i,u,f,s

In [ ]:
import numpy as np

arr=np.array([1,2,3,4], dtype='i4')

print(arr)
print("\n",arr.dtype)

[1 2 3 4]

 int32


**what if a value can not be converted**

- if a type is given in which elements cant be casted then numpy will raise a value error
- **valueerror:**  in python valueerror is raised when type of passed argument to a function is unexpected/incorrect

In [ ]:
# a non integer string like 'a' can not be converted to integer (will raise an error):
import numpy as np

# arr=np.array(['a','2','3'],dtype='i')  # value error: invalid literal for int() with base 10: 'a'

# converting Data type on existing array

In [ ]:
# change the data type from to integer by using 'i' as parameter value:

import numpy as np

arr=np.array([1.1,2.1,3.1])

print(arr)
print(type(arr))
print(arr.dtype)

print('')

newarr=arr.astype('i')

print(newarr)
print(type(newarr))
print(newarr.dtype)

[1.1 2.1 3.1]
<class 'numpy.ndarray'>
float64

[1 2 3]
<class 'numpy.ndarray'>
int32


In [ ]:
# change data type from float to integer by using int as parameter value

import numpy as np
arr=np.array([1.1,2.1,3.1])

newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# change data type from integer to bolean

import numpy as np

arr=np.array([1,0,3])
ar=np.array([1,0,3,6,2])

narr=arr.astype(bool)
xarr=ar.astype(bool)

print(narr)
print(narr.dtype)

print(xarr)
print(xarr.dtype)

[ True False  True]
bool
[ True False  True  True  True]
bool


# Numpy array copy vs view

- [**copy**] the copy should not be affected by changes made to the original array

- [**view**] the view should be affected by the changes made to the original array

In [ ]:
# creat copy

import numpy as np

arr=np.array([1,2,3,4,5])

x=arr.copy()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# create view
# the original array affect when view change

import numpy as np

ar=np.array([1,2,3,4,5])
x=ar.view()
ar[0]=42
x[2]=8

print(ar)
print("\n",x)

[42  2  8  4  5]

 [42  2  8  4  5]


check if array owns its data

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])

x=arr.copy()
y=arr.view()

print(x.base)  # copy owns the data, so it return none
print(y.base)  # view owns the data, so it returns the original array

None
[1 2 3 4 5]


# **numpy array shape**

- **shape of an array**
    - the shape of an array is the number of elements in each dimension

In [ ]:
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


create an array with 5 dimensional using bdim using a vector with values 1,2,3,4 and verify that last dimension has value 4

In [ ]:
import numpy as np

arr=np.array([1,2,3,4], ndmin=5)

print(arr)
print("shape of array: ",arr.shape)

[[[[[1 2 3 4]]]]]
shape of array:  (1, 1, 1, 1, 4)


In [ ]:
import numpy as np

a=np.array([5,99,100,101,3], ndmin=7)

print(a)
print("shape: ",a.shape)

[[[[[[[  5  99 100 101   3]]]]]]]
shape:  (1, 1, 1, 1, 1, 1, 5)


# **Reshaping arrays**
   - reshaping means changing the shape of an array
   - shape of an array is the number of elements in each dimension

In [ ]:
# reshape 1-d to 2-d
# 1-D array with 12 elemnts into 2-d

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr=arr.reshape(4,3)

print(arr)
print("\n",newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# reshape from 1-d to 3-d
# 1-D array with 12 elemnts into 3-d

import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr=a.reshape(2,3,2)

print(a)
print("\n",newarr)     # the outmost dimension have 2 arrays that contain  arrays, each with 2 elements

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**can we reshape into any shape ?**

   - yes, as long as the elements reqyired for reshaping are equal in both shapes

In [ ]:
# import numpy as np
# arr=np.array([1,2,3,4,5,6,7,8])
# nwarr=arr.reshape(3,3)
# print(nwarr)

# **returns copy or view ?**



In [ ]:
# check if the returned array is a copy or view

import numpy as np

a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,4)
print(b)
print(b.base)    # 'B' is view of the original array(a)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


# **unknown dimension**
   - you are allowed to have one "unknown" dimension
   - maning thatyou do not have to specify an exact number for one of the dimensions in the reshape method
   - pass the -1 as the value, and numpy will calculate this number for you
   - **Note: we cannot pass -1 to more than one dimension**

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,2,-1)  # we dont kmow how much coloumns , then pass -1 to it

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(-1,4)

print(b)

[[1 2 3 4]
 [5 6 7 8]]


# **Flattening the arrays**
  - falttering array means **converting a multidimensional array into 1-d**
  - we can use reshape(-1) to do this

In [ ]:
# converting 2-d array to 1-d array

import numpy as np

a=np.array([[1,2,3],[4,5,6]])

na=a.reshape(-1)

print(a)
print("\n converted array: ",na)

[[1 2 3]
 [4 5 6]]

 converted array:  [1 2 3 4 5 6]


In [ ]:
# converting 3-d to 1-d

import numpy as np

a=np.array([[[1,2,3],[4,5,6]],
            [[4,3,2],[3,5,8]]])

b=a.reshape(-1)

print(a)
print("\n converted array: ",b)

[[[1 2 3]
  [4 5 6]]

 [[4 3 2]
  [3 5 8]]]

 converted array:  [1 2 3 4 5 6 4 3 2 3 5 8]


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9], ndmin=3)

b=arr.reshape(-1)

print(arr)
print("\n",b)

[[[1 2 3 4 5 6 7 8 9]]]

 [1 2 3 4 5 6 7 8 9]


# **numpy array iterating**

  - iterating means **going through elements one by one**
  - as we deal with multi-dimensional arrays in numpy, we can do this basic for loop of python

iterating 1-d array

In [ ]:
# iterating 1-d array

import numpy as np

arr=np.array([1,2,3])

for x in arr:
  print(x)

1
2
3


**iterating on 2-d array :** it will goes through rows

In [ ]:
# iterating on 2-d array it will goes through rows

import numpy as np

a=np.arange(6).reshape(2,3)

for x in a:
  print(x)


[0 1 2]
[3 4 5]


iterating each element on 2-d array (scalars)

In [ ]:
# iterating 2-d array

import numpy as np

a=np.arange(6).reshape(2,3)

for x in a:
  for y in x:
    print(y)


0
1
2
3
4
5


**iterating on 3-d array :** it will goes through layers

In [ ]:
# in a 3-d array it will go through all the 2-d array (layers)

import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])

for x in arr:
  print("\n",x)



 [[1 2 3]
 [4 5 6]]

 [[ 7  8  9]
 [10 11 12]]


**iterating on 3-d array :** down to elements (scalars)

In [ ]:
# in a 3-d array iterating down to scalars

import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)


1
2
3
4
5
6
7
8
9
10
11
12


# **iterating array using nditer()**
  - the function nditer() is a helping function that can be used from very basic to very advanced iteration

iterating on each scalar element

In [ ]:
# iterate through the following 3-d array:

import numpy as np

ar=np.array([[[1,2],[3,4]],
             [[5,6],[7,8]]])

for x in np.nditer(ar):
  print(x)

1
2
3
4
5
6
7
8


**Iterating array with different data type**
  - can use **op_dtypes argument** and pass it the expected data type to change the data type of element while iterating
  - numpy does not change the data type of the element in-place (where the elements is in array) so it needs some other space to perform this action , that extra space called **buffer**, and in order to enable it in **nditer() we pass flags=['buffered']**

In [ ]:
import numpy as np

arr=np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

# string prefixed with b is a bytes object

b'1'
b'2'
b'3'


In [ ]:
import numpy as np

arr=np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['complex']):
  print(x)

(1+0j)
(2+0j)
(3+0j)


**iterating with different step size**
  - we can use fitering and followed by iteration

In [ ]:
import numpy as np

a=np.array([[1,2,3,4],
            [5,6,7,8]])

for x in np.nditer(a[:,::2]):
  print(x)

1
3
5
7


In [ ]:
import numpy as np

a=np.array([[1,2,3,4],
            [5,6,7,8]])

for x in np.nditer(a[:1,:]):
  print(x)
print('')
for y in np.nditer(a[1:,:]):
  print(y)
print('')
for z in np.nditer(a[:,2:]):
  print(z)
print('')
for v in np.nditer(a[:2,:2]):
  print(v)
print('')
for s in np.nditer(a[:,1:]):
  print(s)

1
2
3
4

5
6
7
8

3
4
7
8

1
2
5
6

2
3
4
6
7
8


In [ ]:
import numpy as np

a=np.array([[1,2,3,4],
            [5,6,7,8]])

for x in np.nditer(a[0]):
  print(x)
print('')
for y in np.nditer(a[1]):
  print(y)
print('')
for z in np.nditer(a[:,2:]):
  print(z)

1
2
3
4

5
6
7
8

3
4
7
8


# **enumerated iteration using ndenumerate()**
  - enumeration means mentioning sequence number of somthing one by one
  - something we **require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecase**

In [ ]:
import numpy as np

arr=np.array([1,2,3])

for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8]])

for x,y in np.ndenumerate(a):
  print(x,y)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
import numpy as np

arr=np.arange(12).reshape(2,2,3)
print(arr,"\n")

for idx,x in np.ndenumerate(arr):
  print(idx,x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 

(0, 0, 0) 0
(0, 0, 1) 1
(0, 0, 2) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(1, 0, 0) 6
(1, 0, 1) 7
(1, 0, 2) 8
(1, 1, 0) 9
(1, 1, 1) 10
(1, 1, 2) 11


# **Numpy array joining**

  - joining means putting contents of two or more arrays in a single array
  - concatenate () function

joining two array:

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.concatenate((a,b))
print(ab)

ba=np.concatenate((b,a))
print("\n",ba)

[1 2 3 4 5 6]

 [4 5 6 1 2 3]


joining two 2-d array along (axis=1):

In [ ]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

ab=np.concatenate((a,b),axis=1)
print(ab)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

ab=np.concatenate((a,b))
print(ab)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


understanding axis and its role:

  - **axis=0**
       - joins along the rows ( vertically )


  - **axis=1**
      - join along the columns ( horizontally )     

In [ ]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[5,6],[7,8]])

ab=np.concatenate((a,b,c),axis=1)
print(ab)

[[1 2 5 6 5 6]
 [3 4 7 8 7 8]]


# **joining arrays using stack function**

  - stack is the same as the concatenation, the **only difference is that stacking is done along a new axis**
  - concatenate two 1-d array along the second axis which result in putting them one over the other , ie.stacking
  - **stack() methond along with the axis. if axis is not explicity oassed it is taken as 0**

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([5,6,7])

ab=np.stack((a,b),axis=1)
print(ab)

[[1 5]
 [2 6]
 [3 7]]


In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a)
print("\n",b)

print("\n----------by using stack (axis=1)-------------\n")
a_stack=np.stack((a,b),axis=1)
print(a_stack)

print("\n----------by using stack (axis=0)-------------\n")
b_stack=np.stack((a,b),axis=0)
print(b_stack)

print("\n----------by using concatenate (by default or axis=0)----------\n")
a_conct=np.concatenate((a,b))
print(a_conct)

[1 2 3]

 [4 5 6]

----------by using stack (axis=1)-------------

[[1 4]
 [2 5]
 [3 6]]

----------by using stack (axis=0)-------------

[[1 2 3]
 [4 5 6]]

----------by using concatenate (by default or axis=0)----------

[1 2 3 4 5 6]


**stacking along rows**
  - **hstack()** to stack along rows

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.hstack((a,b))
print(ab)

[1 2 3 4 5 6]


**stacking along columns**
  - **vstack()** to stack along columns

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.vstack((a,b))
print(ab)


[[1 2 3]
 [4 5 6]]


**stacking along height (depth)**
  - **dstack()** to stack along height, ehich is the same as depth

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

ab=np.dstack((a,b))
print(ab)


[[[1 4]
  [2 5]
  [3 6]]]


# **numpy array spllitting**

- splitting is reverse  operation of joining
- we use **array_split()**

In [ ]:
# split the array in 3 parts:

import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr, 3)
print(newarr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
newarr=np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5])]


**split into arrays**
  - the return value of array of the array_split() method is an array containing each of the split as an array
  

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

newarr=np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

print("---------------------if using unpacking and printing----------------------------")

print(*newarr) # unpacking and printing

[1 2]
[3 4]
[5 6]
---------------------if using unpacking and printing----------------------------
[1 2] [3 4] [5 6]


**splitting 2-d arrays**


In [ ]:
# split the 2-d array into three 2-d array

import numpy as np

a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(a)
print(a.shape)
print("-------------------------------------")
b=np.array_split(a, 3)
print(b)
print(type(b))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(6, 2)
-------------------------------------
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
<class 'list'>


Split the 2-D array into three 2-D arrays. (this time each element in the 2-D arrays contains 3 elements.)  ?

In [ ]:
import numpy as np

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(a)

na=np.array_split(a, 3)
print(na)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


Split the 2-D array into three 2-D arrays along rows. (returns three 2-D arrays, but they are split along the row (axis=1).).?


In [ ]:
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.array_split(arr, 3, axis=1)
print(newarr)
#print(*newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# **an alternate solution is using hsplit() opposite of hstack()**

  - use the hsplit() method to split the 2-d array into three  2-d arrays along rows

In [ ]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(arr)
print('-------------------------------------------------------')

nwarr=np.hsplit(arr,3)         # same as array_split(arr,3, axis=1)
print(nwarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
-------------------------------------------------------
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


  - use the vsplit() method to split the 2-d array into three  2-d arrays along columns

In [ ]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(arr)
print('--------------------------------------------------------')

nwarr=np.vsplit(arr,3)            # same as array_split(arr,3, axis=0)
print(nwarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
--------------------------------------------------------
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
import numpy as np

arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]])
print(arr)
print('--------------------------------------------------------')

nwarr=np.dsplit(arr,3)
print(nwarr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]
--------------------------------------------------------
[array([[[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]]), array([[[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]]), array([[[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]])]


# **Numpy searching array**

  - you can search an array for a certain value, and return the indexes that get a match
  - to search an array, use the **where() method**

1.find the indexes where the value is 4:

In [ ]:

import numpy as np

a=np.array([1,2,3,4,5,4,4])
x=np.where(a==4)
print(x)

(array([3, 5, 6]),)


2.find the indexes where the values are even:

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8])

x=np.where(a%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
import numpy as np

a=np.array([206,205,201,200,600])

x=np.where(a%2==0)
print(x)

# out put is index number of all even numbers

(array([0, 3, 4]),)


3.find the indexes where the values are odd:

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8])

x=np.where(a%2==1)
print(x)

(array([0, 2, 4, 6]),)


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8])

x=np.where(a%2!=0)
print(x)

(array([0, 2, 4, 6]),)


# **Search sorted**

  - There is a method called searchsorted() which performs a binary search in the array, and **returns the index where the specified value would be inserted to maintain the search order**.
  - **The searchsorted() method is assumed to be used on sorted arrays**.

1.find the index where the value 7 would be inserted:

In [ ]:
import numpy as np

a=np.array([6,7,8,9])

x=np.searchsorted(a, 7)
print(x)

1


In [ ]:
import numpy as np

a=np.array([6,7,8,9])

x=np.searchsorted(a, 7)
print(x)

1


**Search From the Right Side**

  • By default the left most index is returned, but we can give side='right' to return the right most index instead.


1. Find the indexes where the value 7 should be inserted, starting from the right:

In [ ]:
import numpy as np

abc=np.array([6,7,8,9,10])

# Using the right side
# here the element that to be added is looked from the right side of the array
# And place according to the order
# And after that index number is given (as usual as it will only begin from the left side)

x=np.searchsorted(abc, 7, side="right")
print(x)

2


In [ ]:
import numpy as np

ar=np.array([6,7,8,9])

y=np.searchsorted(ar,10, side='right')
print(y)

4


In [ ]:
import numpy as np

ar=np.array([6,7,8,9])

y=np.searchsorted(ar,10)
print(y)

4


**multiple values**

In [ ]:
import numpy as np

arr=np.array([1,3,5,7])

x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


In [ ]:
import numpy as np

arr=np.array([1,3,5,7])

x=np.searchsorted(arr,[2,4,6], side='right')
print(x)

[1 2 3]


In [ ]:
import numpy as np
# here the array is not sorted, so searchsorted() would give unexpected output
# hence use searchsorted on sorted array


a=np.array([7,1,5,3])

x=np.searchsorted(a, [2,4,6])
print(x)

[2 4 4]


- 2 is placed at index **2** because it should **come after 1 and before 5**.
- 4 is placed at index **4** because it should **come after the last element 3**.
- 6 is also placed at index **4**, as it would **come after the last element 3**.
- In summary, while **the searchsorted() function can still technically operate on an unsorted array, the results may not be meaningful in the context of maintaining order, as the function assumes the array is sorted**.

# **numpy sorting array**

 - sorting means putting elements in an **ordered sequence**
 - Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
 - The NumPy ndarray object has a function called sort(), that will sort a specified array.
 - the method give copy of the array

sort the array:

In [ ]:
import numpy as np

arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


***You can also sort arrays of strings, or any other data type:***

sort the array alphabatically:

In [ ]:
import numpy as np

a=np.array(['banana','cherry','apple'])

print(np.sort(a))

['apple' 'banana' 'cherry']


sort a boolean array:

In [ ]:
import numpy as np

ar=np.array([True,False,True])

print(np.sort(ar))

[False  True  True]


**sorting a 2-d array**
  - if you use the sort() method on a 2-d array, both array will be sorted

In [ ]:
import numpy as np

arr=np.array([[3,2,4],[5,0,1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# **Numpy filter array**

  - Getting some elements out of an existing array and creating a new array out of them is called filtering.
  -  In NumPy, you filter an array using a boolean index list.
  - A boolean index list is a list of booleans corresponding to indexes in the array.
  - If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

create an array from the element on index 0 and 2:


In [ ]:
import numpy as np

arr= np.array([41,42,43,44])

x=[True, False, True, False]

newarr=arr[x]
print(newarr)
# because the new array contains only the value where the filter array had the value True, in thios case, index 0 and 2:

[41 43]


# **crating the filter array**

In [ ]:
import numpy as np

arr=np.array([41,42,43,44])

# create a empty list
filter_arr=[]

# go through each elements
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr=arr[filter_arr]

print("original array: ",arr)
print("\n boolean array: ",filter_arr)
print("\n filtered new array: ",newarr)

original array:  [41 42 43 44]

 boolean array:  [False, False, True, True]

 filtered new array:  [43 44]


return only even numbers

In [ ]:
import numpy as np

a=np.array([67,76,89,73,12,14,13])

bool_arr=[] # empty list for adding boolean values

for x in a:
  if x%2==0:
    bool_arr.append(True)
  else:
    bool_arr.append(False)


newarr=a[bool_arr]

print("original array :",a)
print("\n boolean array :",bool_arr)
print("\n even numbers :",newarr)

original array : [67 76 89 73 12 14 13]

 boolean array : [False, True, False, False, True, True, False]

 even numbers : [76 12 14]


**creating filter directly from array**

In [ ]:
import numpy as np

a=np.array([41,42,43,44])

# giving condition directly to the array
filter_a= a > 42   # give output True or False

newa=a[filter_arr]

print("original array :",a)
print("\n checking :",filter_a)
print("\n a > 42 :",newa)

original array : [41 42 43 44]

 checking : [False False  True  True]

 a > 42 : [43 44]


return odd elements

In [ ]:
import numpy as np

a=np.array([41,42,43,44])

b= a%2==1

c=a[b]

print(a)
print(b)
print(c)

[41 42 43 44]
[ True False  True False]
[41 43]


# **Random numbers in Numpy**

**What is a Random Number?**
- Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

**Pseudo Random and True Random**
- **If there is a program to generate random number it can be predicted, thus it is not truly random**.
- **Random numbers generated through a generation algorithm are called pseudo random**.

**Can we make truly random numbers?**
- Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.
- We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

**We will be using pseudo random numbers**.

1.generate a random integer from 0 to 100:

In [ ]:
from numpy import random

x=random.randint(100)
print(x)

11


In [ ]:
import numpy as np

x=np.random.randint(100)
print(x)

60


# **generate random float**

  - the random module's **rand()** method returns a **random float b/w 0 and 1**

2.genarate a random flooa from 0 to 1:


In [ ]:
from numpy import random

x=random.rand(10)
print(x)

[0.05045296 0.32858051 0.92137914 0.3425779  0.50272448 0.19752342
 0.45062974 0.95100369 0.61819133 0.92460097]


# generate Random array

Integers
 - The **randint()** method takes a size parameter **where you can specify the shape of an array**.

1.Generate a 1-D array containing 5 random integers from 0 to 100:

In [ ]:
from numpy import random

x=random.randint(100, size=(5))
print(x)

[31 55 46 43 51]


2.Generate a 2-D array containing 3 rows each contain 5 elements integers from 0 to 100:

In [ ]:
from numpy import random

x=random.randint(100, size=(3,5))
print(x)

[[5 5 7 3 3]
 [5 7 7 3 5]
 [5 3 7 3 9]]


3.Generate a 3-D array containing:

In [ ]:
from numpy import random

x=random.randint(100, size=(2,3,3))
print(y)

[[[68 64 35]
  [61 15 10]
  [63 93 46]]

 [[84  3 72]
  [43 75 82]
  [82 22 46]]]


# **Floats**
- The rand() method also allows you to specify the shape of the array.


 1.Generate a 1-D array containing 5 random floats:

In [ ]:
from numpy import random

x=random.rand(5)

print(x)

[0.11458094 0.00828451 0.20062226 0.43797474 0.00199265]


2.Generate a 2-D array with 3 rows, each row containing 5 random numbers:

In [ ]:
from numpy import random

x=random.rand(3,5)

print(x)

[[0.10137088 0.15301711 0.69393386 0.63161933 0.8418064 ]
 [0.51587805 0.03970861 0.14289104 0.17904803 0.57608186]
 [0.35968015 0.42717957 0.33308265 0.46260443 0.18098202]]


3.Generate a 3-D array :

In [ ]:
from numpy import random

x=random.rand(2,3,3)

print(x)

[[[0.83048556 0.91116454 0.60236681]
  [0.56869874 0.4797365  0.78473937]
  [0.73976281 0.68577196 0.44209243]]

 [[0.10481907 0.96844048 0.38633704]
  [0.02468809 0.55876154 0.40718237]
  [0.05023729 0.04787749 0.77133145]]]


**Generate Random Number From Array**
- The choice() method allows you to generate a random value based on an array of values.
- The choice() method takes an array as a parameter and randomly returns one of the values.

1.Return one of the values in an array:

In [ ]:
from numpy import random

a=random.choice([3,5,7,9])

print(a)

3


- The choice() method also allows you to return an array of values.
- Add a size parameter to specify the shape of the array.

2.genarate a 2-d array that consists of the values in the arrray aprameter (3,5,7, and 9)

In [ ]:
from numpy import random

x=random.choice([3,5,7,9], size=(3,5))
print(x)

[[7 9 7 3 3]
 [5 3 9 9 9]
 [9 9 5 3 7]]


# **Random Permutations**



**Random Permutations of Elements**

  - A **permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.**
  - The NumPy Random module provides two methods for this: **shuffle() and permutation().**

## **Shuffling Arrays**
  - Shuffle means changing arrangement of elements in-place. i.e. in the array itself.
  
**The shuffle() method makes changes to the original array.**

In [ ]:
from numpy import random
import numpy as np

ar=np.array([1,2,3,4,5])

random.shuffle(ar)
print(ar)

[4 5 2 1 3]


**Genarating permutation os arrays**

  - The permutation() method returns a re-arranged array (and leaves the original array un-changed).

genarate a random permutation of elements of following array:

In [ ]:
from numpy import random
import numpy as np

a=np.array([1,2,3,4,5])

print(random.permutation(a))

[4 2 3 5 1]
